# Generated by Django 5.2.6 on 2025-12-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_autor_bibliografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('Ver_prestamos', 'Puede ver prestamos'), ('gestionar_prestamos', 'Puede gestionar prestamos'))},
        ),
    ]
