# Generated by Django 5.2.6 on 2025-12-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('Ver_prestamos', 'Puede ver prestamos'), ('gestionar_prestamos', 'Puede gestionar prestamos'), ('gestionar_libros', 'Puede gestionar libros'))},
        ),
    ]
