# Generated by Django 4.2.27 on 2026-01-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_libro_coverid_libro_descripcion_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='fechaPago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
