# Generated by Django 4.2.27 on 2026-01-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_multa_fechapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
