# Generated by Django 4.2.27 on 2026-01-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_libro_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
