# Generated by Django 4.2.27 on 2026-01-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
