# Generated by Django 4.2.27 on 2026-01-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_autor_activo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='multa',
            constraint=models.UniqueConstraint(fields=('prestamo', 'tipo'), name='uniq_multa_por_prestamo_y_tipo'),
        ),
    ]
