# Generated by Django 4.2.27 on 2026-01-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_ajustar_permisos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
